### PR TITLE
karin: add barrier for other devices

### PR DESCRIPTION
**Pull request by andi34**
Change-Id: I1c7604b386a6e8086949605d28bab9ff17fca343

### CODE REVIEW

**Comment by andi34** [comment]
also add barrier for other devices

**Comment by andi34** [comment]
SONY_ROOT shouldn't be defined if AOSP way will be followed, only barrier

**Comment by andi34** [comment]
Force pushed, also follow AOSP way

**Comment by alviteri** [comment]
@andi34 do you see another Android.mk into this device tree?

**Pull request closed without merging**
